### ISSUE TITLE
客户端没法代理登陆.

### ISSUE THREAD

**Issue by just2ciao** [anosora233/richi-console#1]
![image](https://github.com/anosora233/richi-console/assets/33555873/a1680b0a-a35a-48ba-bfb0-fbf89b133df7)

**Comment by anosora233** [comment]
禁用 IPv6 、或者配置 upstream_proxy 试试？
目前最新的功能还没有打包，直接 clone 仓库
在命令行运行 python richi-console.py

**Comment by just2ciao** [comment]
> 禁用 IPv6 、或者配置 upstream_proxy 试试？ 目前最新的功能还没有打包，直接 clone 仓库 在命令行运行 python richi-console.py

![image](https://github.com/anosora233/richi-console/assets/33555873/d4aecda8-1b60-494f-9b00-299eb9cf070b)
下载了最新版0.3的解压使用.可以正确响应了.但启动时不会自动打开小助手.所以还是没法使用

**Comment by anosora233** [comment]
小助手和皮肤都是默认不启用的
请根据需求修改配置文件 settings.json

**Comment by just2ciao** [comment]
> 

成功启动并使用了.感谢
