### ISSUE TITLE
本地昵称失效了，装扮不全

### ISSUE THREAD

**Issue by lqgl** [anosora233/richi-console#14]
更新后，似乎不会直接走修改昵称请求，而是需要先购买改名卷轴。装扮不全，无法使用部分较新的装扮。

**Comment by lqgl** [comment]
本地昵称可以通过手动修改account/xxx.json中的nickname实现，但是还是希望作者能够一起更新一下。

**Comment by anosora233** [comment]
虽然还有很多问题，暂时就先这样处理。 :joy:

**Comment by lqgl** [comment]
你好，你的邮件我已收到。

**Comment by lqgl** [comment]
非常感谢，在我本地也正常运行。👍
